### ISSUE TITLE
Voir dernier pli

### ISSUE THREAD

**Issue by gaut-b** [augnustin/coinche.me#25]

**Comment by augnustin** [comment]
En gros, pour cette action, je pense qu'elle est 100% locale : c'est pas pke un joueur regarde le dernier pli que les autres veulent faire pareil.

Du coup, je dirais que soit on le stocke dans le store local, soit carrément juste dans le state du game.

**Comment by augnustin** [comment]
Et en terme d'interface il faut bien que l'on comprenne qu'on est en mode visualisation, pas jeu, du coup faut que ce soit bien différent des cartes déjà jouées sur la table. 
Comme ça, je verrais bien une sorte de modale.

**Comment by augnustin** [comment]
Mais on peut commencer par juste faire un composant puis on verra pour l'interface.

**Comment by gaut-b** [comment]
> En gros, pour cette action, je pense qu'elle est 100% locale : c'est pas pke un joueur regarde le dernier pli que les autres veulent faire pareil.
> 
> Du coup, je dirais que soit on le stocke dans le store local, soit carrément juste dans le state du game.

C'est déjà le cas. Tu as un array "tricks" dans le state global, qui contient tous les plis. Il suffit juste de récupérer le dernier, et sauf erreur e ma part j'ai déjà codé le sélecteur qui permet de le faire. Donc il reste juste de l'UI à faire
