### ISSUE TITLE
écran vide à la création d'une table

### ISSUE THREAD

**Issue by jrdoublet** [augnustin/coinche.me#47]
Bonjour,
j'ai tenté de lancer le coincheur avec docker-compose sur ubuntu
cependant à la création d'une table, après avoir renseigné mon nom et cliqué sur "créer une table",
j'arrive sur un écran vert dans lequel aucune action n'est possible
l'url de cet écran est http://localhost:3000/game/jrjr

voici les logs docker :

```
 Le coincheur listening on port 3000!
app_1    | New socket connection oaBCyzacwjSnhdg2AAAA s:I4sG_3gLsq9CqagN2-0drttiTd-diojQ.rdqOm39Lsg/VJjiPvtuEjGB11C11+N58vBBC1+SCwgQ
app_1    | Action on table jrjr {
app_1    |   type: 'JOIN',
app_1    |   payload: {
app_1    |     playerId: 's:I4sG_3gLsq9CqagN2-0drttiTd-diojQ.rdqOm39Lsg/VJjiPvtuEjGB11C11+N58vBBC1+SCwgQ',
app_1    |     socketId: 'oaBCyzacwjSnhdg2AAAA',
app_1    |     playerName: 'jr'
app_1    |   }
app_1    | }
app_1    | playerId not found in players oaBCyzacwjSnhdg2AAAA
app_1    | disconnected oaBCyzacwjSnhdg2AAAA
app_1    | Action on table jrjr { type: 'LEAVE', payload: 'oaBCyzacwjSnhdg2AAAA' }
```

**Comment by augnustin** [comment]
Hello,

Comme ça, ça ne me dit rien. Je suspecterais surtout un problème côté front. Du coup si tu peux ouvrir la console du navigateur et copier les messages qui s'y trouve ça me permettrait de t'aider à investiguer.

En revanche, je me rends compte que je n'avais pas mergé la dernière version en prod sur master donc ça peut être à l'origine du problème. Je viens de le faire donc tu peux récupérer la dernière version (`git pull origin master`) et voir si ça résout le problème.

Bonne change

**Comment by jrdoublet** [comment]
Bonjour,
l'upgrade a quasiment tout réglé, je n'ai plus que les enchères avec annonces qui plantent, toujours le même pb de session mais ce n'est pas bloquant de mon point de vue.

**Comment by augnustin** [comment]
Ok super. 
En effet, les enchères avec annonces et décompte de points ne sont pas tout-à-fait exemptes de bugs. Ca sera peut-être pour un troisième confinement ... bref il ne vaut ptet mieux pas que ça sorte !
